public class DemoApex28072023 {
    public static void method(){
        System.debug('This is a demo method and in demo class');
        System.debug('This is a demo method and in demo class');
    }
    public static void method2(){
        System.debug('This is a demo method and in demo class');
        System.debug('This is a demo method and in demo class');
        
    }
    public static void method3(){
        System.debug('This is a demo method and in demo class');
        System.debug('This is a demo method and in demo class');
        
    }
    public static void method4(){
        System.debug('This is a demo method and in demo class');
        System.debug('This is a demo method and in demo class');
        
    }
}